version: '3.0'
services:
  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins-data:/var/lib/jenkins/

  api-catalog-db:
    container_name: api-catalog-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_catalog'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
     - 3310:3306

volumes:
  jenkins-data:
