pipeline {
    agent any
    tools {
        maven 'Maven 3.3.3'
    }
    stages {
        stage('Compile') {
            steps {
                dir('api-catalog') {
                    sh 'mvn clean compile'
                }
            }

        }
        stage('Unit Test') {
            steps {
                dir('api-catalog') {
                    sh 'mvn test'
                }
            }
        }
        stage('OWASP Dependency-Track Vulnerabilities') {
            steps {
                dir('api-catalog') {
                    sh 'mvn -B -DskipTests package'
                    dependencyTrackPublisher artifact: 'target/bom.xml', synchronous: true, dependencyTrackApiKey: 'Nxyyp59CY7Aackh4vPFAhbbfaRSG3e3l'
                }
            }
        }
        stage('Package') {
            steps {
                dir('api-catalog') {
                    sh 'mvn package'
                }
            }
        }
    }
}