pipeline {
    agent any
    tools {
        maven 'Maven 3.3.3'
    }
    stages {
        stage('Compile') {
            steps {
                dir('api-catalog') {
                    sh 'mvn clean compile'
                }
            }

        }
        stage('Unit Test') {
            steps {
                dir('api-catalog') {
                    sh 'mvn test'
                }
            }
        }
        stage('Package') {
            steps {
                dir('api-catalog') {
                    sh 'mvn package'
                }
            }
        }
        stage('OWASP Dependency-Track Vulnerabilities') {
            steps {
                dir('api-catalog') {
                    sh 'mvn -B -DskipTests package'
                    dependencyTrackPublisher artifact: 'target/bom.xml', projectId: 'ad14ba42-c4c1-4184-9d58-ccc0005ffa3f', synchronous: true, dependencyTrackApiKey: 'sAHfRePHbRPQ4kZiI1iyjNTMfyXEWgCo'
                }
            }
        }
    }
}